// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk5pLJupfQ6EQotYY6tIH5MW0NP4DqnFs',
    appId: '1:901677971052:web:cce9d0361f05e68478ca49',
    messagingSenderId: '901677971052',
    projectId: 'ditonton-9f08e',
    authDomain: 'ditonton-9f08e.firebaseapp.com',
    storageBucket: 'ditonton-9f08e.appspot.com',
    measurementId: 'G-T29V749CRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFraymOU_CShEd1Y_lQbur9zDuac7WPEg',
    appId: '1:901677971052:android:bd4143348bff910578ca49',
    messagingSenderId: '901677971052',
    projectId: 'ditonton-9f08e',
    storageBucket: 'ditonton-9f08e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaXgQp366eKKQerNQIIsG1IX1Acb2RaqI',
    appId: '1:901677971052:ios:cfc449b1534430a378ca49',
    messagingSenderId: '901677971052',
    projectId: 'ditonton-9f08e',
    storageBucket: 'ditonton-9f08e.appspot.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
